version: '3.9'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passs
      POSTGRES_DB: gaddrdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
